### ISSUE TITLE
Fatal error: undefined function BrightNucleus\Boilerplate\Scripts\_()

### ISSUE THREAD

**Issue by GaryJones** [brightnucleus/boilerplate#4]
```
Now running setup tasks...
PHP Fatal error:  Uncaught Error: Call to undefined function BrightNucleus\Boilerplate\Scripts\_() in /Users/gary/code/my-test-plugin/_scripts/Setup.php:54
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(255): BrightNucleus\Boilerplate\Scripts\Setup::run(Object(Composer\Script\Event))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('BrightNucleus\\B...', 'run', Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(95): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(237): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-create-pro...', true)
#4 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(142): Composer\Command\CreateProjectCommand->installProject(Object(Comp in /Users/gary/code/my-test-plugin/_scripts/Setup.php on line 54
```

**Comment by schlessera** [comment]
This is probably caused by `gettext` not being included in your local PHP installation.

I just removed all the localization from this package, as I don't think it is that useful anyway in this case.
